![title](imagens/M04-Numpy.jpg)

# Numpy - Uma introdução ao Pacote Numpy - Parte 1

Seja bem-vindo ao universo do NumPy! Aqui, você transcende as limitações das listas Python e adquire o poder de executar operações de array complexas de maneira eficiente, graças à robusta biblioteca NumPy, uma abreviação para "Python Numérico". Neste módulo abrangente e objetivo, embarque conosco para desvendar os segredos do NumPy e desbloquear todo o seu potencial extraordinário.

Serão abordados os seguintes assuntos:

### Índice

#### Parte1: Noções básicas de array Numpy
- 1.1 Compreendendo tipos de dados Numpy
- 1.2 Criando arrays Numpy
- 1.3 Indexação em Arrays NumPy
- 1.4 Funções/Métodos NumPy

#### Parte 2: Operações com Arrays
- 2.1 Operações entre elementos
- 2.2 Anexar e excluir
- 2.3 Funções de agregação e ufuncs
- 2.4 Remodelando arrays

#### Parte3: Trabalhando com Arrays Numpy
- 3.1 Combinando arrays
- 3.2 Dividindo arrays
- 3.3 Alias ​​vs. Visualização vs. Cópia de arrays
- 3.4 Classificando arrays Numpy

#### Parte4: NumPy para limpeza de dados e análise estatística
- 4.1 Identificando valores ausentes
- 4.2 Removendo linhas ou colunas com valores ausentes
- 4.3 Transformação de dados
- 4.4 Amostragem aleatória

#### Parte5: NumPy para Álgebra Linear e Técnicas Avançadas
- 5.1 Operações de Matrizes Complexas
- 5.2 Resolver Equações Lineares
- 5.3 Matrizes Mascaradas
- 5.4 Matrizes Estruturadas


## Parte1: Noções básicas de array Numpy


Os arrays NumPy são projetados para computação numérica e científica , tornando-os ideais para tarefas como análise de dados, aprendizado de máquina e operações matemáticas.

### 1.1 Compreendendo tipos de dados Numpy

Em Numpy Arrays, todos os elementos dentro de um único array devem ter o mesmo tipo de dados. Essa homogeneidade é um dos principais recursos que tornam os arrays NumPy eficientes e adequados para computação numérica, e alguns outros motivos são os seguintes:

- **Eficiência:** Nos bastidores, o NumPy é implementado em C e Fortran, tornando as operações em grandes arrays extremamente rápidas em comparação com o código Python equivalente.
- **Poder matemático:** você não acreditaria na ampla variedade de funções e operações matemáticas disponíveis no Numpy, facilitando tarefas como álgebra linear, estatística e cálculos matemáticos complexos.
- **Interoperabilidade:** NumPy integra-se perfeitamente com outras bibliotecas Python, como Pandas, SciPy e Matplotlib.


In [1]:
#importando o NumPy
import numpy as np

In [2]:
#verificando a versão do numpy
np.__version__

'1.26.4'

In [3]:
# Para instalação de uma versão exata de um pacote Python
# Este módulo foi executado utilizando a versão 1.26.4 do Numpy
# !pip install numpy==1.26.4

### 1.2 Criando arrays Numpy

In [4]:
#Criando um Array a partir de uma lista Python
array1 = np.array([2, 5, 10, 34, 23, 9, 73, 21, 6])

In [5]:
print(array1)

[ 2  5 10 34 23  9 73 21  6]


In [6]:
#Conformando o tipo de dados do array criado
type(array1)

numpy.ndarray

In [7]:
#ndarray - n dimensional array - array de dimensão n

#Vamos ver o formato (shape) desse array
array1.shape

(9,)

In [8]:
# Os arrays são estruturas de dados muito mais eficientes do que os tipos básicos da linguagem Python.

In [9]:
# Criando um array inteiro com dtype explícito, o que não é necessário.
int_array = np.array([ 1 , 2 , 3 ], dtype=np.int32) 

### 1.3 Indexação em Arrays NumPy

In [10]:
print(array1)

[ 2  5 10 34 23  9 73 21  6]


In [11]:
array1[5]

9

In [12]:
# A indexação em Python, com qualquer interável, inicia com ZERO.

# Também posso fazer o fatiamento:
array1[1:4]

array([ 5, 10, 34])

In [13]:
# criando uma lista de índices
indices = [1, 3, 6, 8]

In [14]:
# Imprimindo os elementos com os respectivos índices:
array1[indices]

array([ 5, 34, 73,  6])

In [15]:
# Criando uma máscara (no caso vamos criar uma máscara booleana para os elementos pares)
mascara = (array1 % 2 == 0)

In [16]:
# Vamos ver a máscara criada...
mascara

array([ True, False,  True,  True, False, False, False, False,  True])

In [17]:
# Vamos utilizar a máscara criada como indexador. No caso, ele vai retornar os elementos cujos índices forem verdadeiros.
# Ou seja... vai retornar todos os valore que são pares.
array1[mascara]

array([ 2, 10, 34,  6])

In [18]:
# Utilizamos a indexação também para fazer a substituição de valores...
array1[0] = 200

In [19]:
array1[0] = 'c'

ValueError: invalid literal for int() with base 10: 'c'

In [ ]:
array1

#### Atenção!!!
Não é possível incluir elementos de outros tipos de dados.
Arrays NumPy são todos do mesmo tipo de dado.

### 1.4 Funções/Métodos NumPy

In [20]:
# A função array() cria um array NumPy
array2 = np.array([1,2,3,4,5])

In [21]:
print(array2)

[1 2 3 4 5]


In [22]:
array2.shape

(5,)

In [23]:
# array2 agora é um objeto do tipo nd.array... e portanto possuem uma série de métodos associados a este objeto.
# para visualizar os métodos... digite o nome... ponto... e tecle tab.
array2.

SyntaxError: invalid syntax (2534955207.py, line 3)

In [24]:
#Usando os métodos do array NumPy...
#cumsum --> soma acumulada
array2.cumsum()

array([ 1,  3,  6, 10, 15])

In [25]:
#cumprod --> produto acumulado
array2.cumprod()

array([  1,   2,   6,  24, 120])

In [27]:
# Para verificar as funções disponíveis em NumPy... digite o alias (np) seguido de ponto e tab.
np

<ufunc 'absolute'>

In [28]:
# Função arange --> cria um array NumPy contendo uma progressão aritmética a partir de um intervalo: inicio, fim, passo.
array3 = np.arange(0, 40, 4)

In [29]:
array3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [30]:
# Criar um array preenchido com zeros
array4 = np.zeros(7)

In [31]:
array4

array([0., 0., 0., 0., 0., 0., 0.])

In [32]:
# Criar uma matriz diagonal... 1 nas posições em diagonal e zero nas demais posições
array5 = np.eye(5)

In [33]:
print(array5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
# Podemos passar como parâmetro um array numpy para que o mesmo seja utilizado como diagonal...
array6 = np.diag(np.array([1,2,3,4]))

In [35]:
print(array6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [36]:
# Criação de um array numpy de valores booleanos
array7 = np.array([True, False, False, True])

In [37]:
print(array7)

[ True False False  True]


In [38]:
# Criação de um array numpy de strings
array8 = np.array(['pyPRO', 'Python', 'Profissional'])

In [39]:
print(array8)

['pyPRO' 'Python' 'Profissional']


A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Igualmente distribuidos no intervalo especificado.

In [40]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [41]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


Muito útil para inicializar uma matriz de pesos, em uma rede neural.

A função logspace() é semelhante, só que cria uma sequencia de números espaçados logaritmicamente, dentro de um intervalo especificado.

In [42]:
print(np.logspace(0, 10, 15))

[1.00000000e+00 5.17947468e+00 2.68269580e+01 1.38949549e+02
 7.19685673e+02 3.72759372e+03 1.93069773e+04 1.00000000e+05
 5.17947468e+05 2.68269580e+06 1.38949549e+07 7.19685673e+07
 3.72759372e+08 1.93069773e+09 1.00000000e+10]


Outras funções/métodos Numpy:

- **np.ones:** ones gera um array preenchido com aqueles do formato especificado.
  - `np.ones(shape, dtype=None)`
- **np.zeros_like:** cria um novo array preenchido com zeros, mas com a mesma forma e tipo de dados de um array existente.
- **np.ones_like:** é semelhante a np.zeros_like, mas cria um novo array preenchido com uns em vez de zeros.


In [44]:
# Crie um array 3x3 preenchido com zeros
zeros_arr = np.zeros(( 3 , 3 )) 

In [45]:
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
# Crie uma nova matriz preenchida com zeros, 
# combinando a forma e o tipo de dados da matriz original
zeros_array = np.zeros_like(zeros_arr) 

In [50]:
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
# Crie uma nova matriz preenchido com uns, 
# correspondendo à forma e ao tipo de dados do array original
ones_array = np.ones_like(zeros_arr)

In [53]:
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## FIM