<h2>1.1 Introdução ao Numpy<h2>

In [34]:
# Importando o numpy
import numpy as np

In [35]:
# Verificando a versão 
np.__version__

'2.1.0'

<h2>1.2 Criando arrays com Numpy<h2>

In [36]:
# Criando um array a partir de uma lista no python
array1 = np.array([2, 5, 9, 17, 25, 32, 36, 44, 51])

In [37]:
print(array1)

[ 2  5  9 17 25 32 36 44 51]


In [38]:
# Conformando o tipo de dados do array criado
type(array1)

numpy.ndarray

In [39]:
#ndarray - n dimensional array - array de dimensão n

#Vamos ver o formato (shape) desse array
array1.shape

(9,)

In [40]:
# Criando um array inteiro com dtype explícito, o que não é necessário.
int_array = np.array([1, 2, 3], dtype=np.int32)

In [41]:
print(int_array)

[1 2 3]


<h2>1.3 Indexação em Arrays Numpy<h2>

In [42]:
print(array1)

[ 2  5  9 17 25 32 36 44 51]


In [43]:
array1[4]

np.int64(25)

In [44]:
# A indexação em Python, com qualquer interável, inicia com ZERO.

# Também é possível fatiar o array
array1[3:7]

array([17, 25, 32, 36])

In [45]:
# criando uma lista de índices
indices = [2, 5, 7, 4, 8, 1]

In [46]:
# Imprimindo os elementos com os respectivos índices:
print(array1)
array1[indices]

[ 2  5  9 17 25 32 36 44 51]


array([ 9, 32, 44, 25, 51,  5])

In [47]:
# Criando uma máscara (no caso vamos criar uma máscara booleana para os elementos pares)
mascara = (array1 % 2 == 0)

In [48]:
mascara

array([ True, False, False, False, False,  True,  True,  True, False])

In [49]:
# Vamos utilizar a máscara criada como indexador. No caso, ele vai retornar os elementos cujos índices forem verdadeiros.
# Ou seja... vai retornar todos os valore que são pares.
array1[mascara]

array([ 2, 32, 36, 44])

In [50]:
# Utilizamos a indexação também para fazer a substituição de valores...
array1[0] = 200

<h2>1.4 Funções/Métodos Numpy

In [51]:
# A função array() cria um array NumPy
array2 = np.array([1,2,3,4,5])

In [52]:
print(array2)

[1 2 3 4 5]


In [53]:
array2.shape

(5,)

In [57]:
#Usando os métodos do array NumPy...
#cumsum --> soma acumulada
print(array2)
array2.cumsum()

[1 2 3 4 5]


array([ 1,  3,  6, 10, 15])

In [58]:
#cumprod --> produto acumulado
print(array2)
array2.cumprod()

[1 2 3 4 5]


array([  1,   2,   6,  24, 120])

In [60]:
# Função arange --> cria um array NumPy contendo uma progressão aritmética a partir de um intervalo: inicio, fim, passo.
array3 = np.arange(0, 20, 2)

In [61]:
array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
# Criar um array preenchido com zeros
array4 = np.zeros(5)

In [63]:
array4

array([0., 0., 0., 0., 0.])

In [64]:
# Criar uma matriz diagonal... 1 nas posições em diagonal e zero nas demais posições
array5 = np.eye(5)

In [65]:
array5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
# Podemos passar como parâmetro um array numpy para que o mesmo seja utilizado como diagonal...
array6 = np.diag(np.array([1, 2, 3, 4]))

In [68]:
array6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [69]:
# Criação de um array numpy de valores booleanos
array7 = np.array([True, False, False, True])

In [73]:
print(array7)

[ True False False  True]


In [74]:
# Criação de um array numpy de strings
array8 = np.array(["Alexandre", "Julia", "Arthur", "Henrique"])

In [75]:
print(array8)

['Alexandre' 'Julia' 'Arthur' 'Henrique']


A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Igualmente distribuidos no intervalo especificado.

In [76]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [80]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


Muito útil para inicializar uma matriz de pesos, em uma rede neural.


A função logspace() é semelhante, só que cria uma sequencia de números espaçados logaritmicamente, dentro de um intervalo especificado.


In [83]:
print(np.logspace(0, 10, 10))

[1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
 2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
 7.74263683e+08 1.00000000e+10]


Outras funções/métodos Numpy

- **np.ones:** ones gera um array preenchido com aqueles do formato especificado.
    - `np.ones(shape, dtype=None)`
- **np.zeros_like:** cria um novo array preenchido com zeros, mas com a mesma forma e tipo de dados de um array existente.
- **np.ones_like:** é semelhante a np.zeros_like, mas cria um novo array preenchido com uns em vez de zeros.

In [86]:
# função ones
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [87]:
# Crie um array 3x3 preenchido com zeros
zeros_arr = np.zeros(( 3 , 3 )) 

In [88]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
# Crie uma nova matriz preenchida com zeros, 
# combinando a forma e o tipo de dados da matriz original
zeros_array = np.zeros_like(zeros_arr) 

In [90]:
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [91]:
# Crie uma nova matriz preenchido com uns, 
# correspondendo à forma e ao tipo de dados do array original
ones_array = np.ones_like(zeros_arr)

In [92]:
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<h2>FIM