<h2>2.1 Operações Elementares

In [15]:
import numpy as np

In [16]:
# Criando vetores Numpy 1D
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
escalar = 2

In [17]:
# Adição
result_add = arr1 + arr2
print(result_add)

[5 7 9]


In [18]:
# Multiplicação
result_mult = arr1 * arr2
print(result_mult)

[ 4 10 18]


In [19]:
# Divisão
result_div = result_mult / arr1
print(result_div)

[4. 5. 6.]


In [20]:
# Subtração
result_sub = result_mult - arr1
print(result_sub)

[ 3  8 15]


In [21]:
# Criando vetores Numpy 2D (matrizes)
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])


In [22]:
# Multiplicação (por elemento, não multiplicação de matriz)
result_matriz = matriz1 * matriz2
print(result_matriz)

[[ 5 12]
 [21 32]]


In [23]:
# Multiplicação de matriz real usando np.dot
matriz_multiplicacao = np.dot(matriz1, matriz2)
print(matriz_multiplicacao)

[[19 22]
 [43 50]]


In [24]:
# Broadcasting: Multiplique o array por um resultado escalar
result = arr2 * escalar
print(result)

[ 8 10 12]


<h2>Anexar e Excluir

Para acrescentar matrizes no NumPy, você pode usar a `numpy.append()` função. Esta função permite adicionar elementos ao final de um array existente ao longo de um eixo especificado.

Tenha em mente que `np.append()` retorna um novo array com os elementos anexados; portanto, não modifica os arrays originais. Se quiser modificar uma matriz existente no local, você pode usar métodos como `np.concatenate()` ou usar instruções de atribuição.

Podemos usar `np.delete` para remover os itens de um array.

In [25]:
# Crie um array
original_array = np.array([1, 2, 3])
print(original_array)

[1 2 3]


In [26]:
# Anexar elementos no local 
original_array = np.append(original_array, [4, 5, 6])
print(original_array)

[1 2 3 4 5 6]


In [27]:
# Crie um array Numpy
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [28]:
# Remova o item do indice 2 (valor 3)
new_arr = np.delete(arr, 2)
print(new_arr)

[1 2 4 5]


In [29]:
# Crie um array numpy 2D
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# Remova a segunda linha (indice 1)
new_arr = np.delete(arr, 2, axis=0)
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]]


<h2>2.3 Funções de Agregação de ufuncs(funções universais)

NumPy fornece funções integradas para operações de agregação comuns em matrizes, incluindo média, soma, mínimo, máximo, etc. NumPy também fornece funções universais (ufuncs) que operam em elementos em matrizes, incluindo funções matemáticas, trigonométricas e exponenciais.

In [31]:
# Criando um array Numpy
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [32]:
# Funções de agregração 

mean_value = np.mean(arr)           # média
median_value = np.median(arr)        # mediana
variance = np.var(arr)              # variancia 
standard_deviation = np.std(arr)    # desvião padrão
print('Valor médio: ', mean_value)
print('Mediana: ', median_value)
print('Variância: ', variance)
print('Desvio Padrão: ', standard_deviation)

Valor médio:  3.0
Mediana:  3.0
Variância:  2.0
Desvio Padrão:  1.4142135623730951


In [33]:
sum_value = np.sum(arr)
max_value = np.max(arr)
min_value = np.min(arr)
print('Soma: ', sum_value)
print('Máximo: ', max_value)
print('Minimo: ',min_value)

Soma:  15
Máximo:  5
Minimo:  1


In [34]:
# Funções Universais
sqrt_value = np.sqrt(arr)
exp_value = np.exp(arr)
print('Raiz quadrada: ', sqrt_value)
print('Exponencial..: ', exp_value)

Raiz quadrada:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial..:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


<h2>Remodelando Arrays

Você pode alterar a forma de um array sem alterar seus dados usando o método `reshape`, por exemplo, para achatar um array (convertê-lo em um array 1D) ou alterá-lo para um array de dimensão superior (por exemplo, de 1D para 2D ou de 2D para 3D).

O método `reshape` pode ser particularmente útil quando você precisa preparar dados para diversas operações, como multiplicação de matrizes, convolução ou exibição de imagens.

Para remodelar o método, você pode passar a forma do resultado esperado que deseja. O número total de elementos na matriz original deve corresponder ao número total de elementos na nova forma. Em outras palavras, o produto das dimensões na nova forma deve ser igual ao número total de elementos na matriz original. NumPy gerará um erro se esta condição não for atendida.

In [35]:
# Criando um array 2D
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [36]:
# Aqui como estamos passando apenas 6, ele irá converter o array 2d em 1d array 
# com 6 elementos, você não pode passar nada além de 6, 
# pois não corresponde ao array original! 
arr1D = arr2D.reshape(6)
print(arr1D)

[1 2 3 4 5 6]


In [37]:
# Criando um array 1D
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(arr_1d)

[1 2 3 4 5 6]


In [38]:
# Remodelando para 2D
arr_2d = arr_1d.reshape(2,3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [40]:
# Criando um array 1D com 12 elementos
arr = np.arange(12)
print(arr.shape)

(12,)


In [45]:
# Remodelando em um array 2D com um número desconhecido de colunas (-1)
reformed_arr = arr.reshape(2, -1)
print(reformed_arr.shape)

(2, 6)


<h2>FIM